/**
 * I18nContext.jsx — App-wide internationalisation.
 *
 * Supported languages:
 *   en  English (default)
 *   fr  French
 *   es  Spanish
 *   zh  Chinese (Simplified)
 *   ar  Arabic
 *   it  Italian
 *   de  German
 *
 * Usage:
 *   const { t, lang, setLang } = useI18n();
 *   t('search.title')   →  "Search Questions"  (or translated)
 *
 * Only high-visibility UI strings are translated here — titles, tab labels,
 * buttons, section headers, and key messages. Body prose is generated by AI
 * and already respects the user's topic language.
 */
import React, { createContext, useContext, useState, useCallback } from 'react';

export const LANGUAGES = [
  { code: 'en', name: 'English',            nativeName: 'English',    dir: 'ltr', flag: '🇬🇧' },
  { code: 'fr', name: 'French',             nativeName: 'Français',   dir: 'ltr', flag: '🇫🇷' },
  { code: 'es', name: 'Spanish',            nativeName: 'Español',    dir: 'ltr', flag: '🇪🇸' },
  { code: 'zh', name: 'Chinese',            nativeName: '中文',        dir: 'ltr', flag: '🇨🇳' },
  { code: 'ar', name: 'Arabic',             nativeName: 'العربية',    dir: 'rtl', flag: '🇸🇦' },
  { code: 'it', name: 'Italian',            nativeName: 'Italiano',   dir: 'ltr', flag: '🇮🇹' },
  { code: 'de', name: 'German',             nativeName: 'Deutsch',    dir: 'ltr', flag: '🇩🇪' },
];

// ── Translation strings ───────────────────────────────────────────────────────
const STRINGS = {
  // ── Navigation ──────────────────────────────────────────────────────────
  'nav.home':          { en:'Home',              fr:'Accueil',       es:'Inicio',           zh:'首页',      ar:'الرئيسية',    it:'Home',         de:'Startseite'      },
  'nav.settings':      { en:'Settings',          fr:'Paramètres',    es:'Ajustes',          zh:'设置',      ar:'الإعدادات',   it:'Impostazioni', de:'Einstellungen'   },
  'nav.signIn':        { en:'Sign in',            fr:'Connexion',     es:'Iniciar sesión',   zh:'登录',      ar:'تسجيل الدخول',it:'Accedi',       de:'Anmelden'        },
  'nav.signUp':        { en:'Sign up',            fr:'S\'inscrire',   es:'Registrarse',      zh:'注册',      ar:'إنشاء حساب',  it:'Registrati',   de:'Registrieren'    },
  'nav.signOut':       { en:'Sign out',           fr:'Déconnexion',   es:'Cerrar sesión',    zh:'退出',      ar:'تسجيل الخروج',it:'Disconnetti',  de:'Abmelden'        },

  // ── Tabs ────────────────────────────────────────────────────────────────
  'tab.search':        { en:'Search Questions',  fr:'Chercher',      es:'Buscar',           zh:'搜索题目',  ar:'بحث الأسئلة', it:'Cerca Domande',de:'Fragen suchen'   },
  'tab.subjects':      { en:'My Subjects',       fr:'Mes matières',  es:'Mis asignaturas',  zh:'我的科目',  ar:'موادي',       it:'Le mie materie',de:'Meine Fächer'    },
  'tab.aiNotes':       { en:'AI Notes',          fr:'Notes IA',      es:'Notas IA',         zh:'AI笔记',   ar:'ملاحظات AI',  it:'Note AI',      de:'KI-Notizen'      },
  'tab.timer':         { en:'Study Timer',       fr:'Minuteur',      es:'Temporizador',     zh:'学习计时',  ar:'مؤقت الدراسة',it:'Timer Studio', de:'Lerntimer'       },
  'tab.downloads':     { en:'My Downloads',      fr:'Téléchargements',es:'Descargas',       zh:'我的下载',  ar:'تنزيلاتي',   it:'Download',     de:'Downloads'       },
  'tab.favourites':    { en:'Favourites',        fr:'Favoris',       es:'Favoritos',        zh:'收藏',      ar:'المفضلة',    it:'Preferiti',    de:'Favoriten'       },
  'tab.history':       { en:'History',           fr:'Historique',    es:'Historial',        zh:'历史',      ar:'السجل',      it:'Cronologia',   de:'Verlauf'         },

  // ── Hub pages ──────────────────────────────────────────────────────────
  'hub.igcse':         { en:'IGCSE Study Hub',   fr:'Hub IGCSE',     es:'Hub IGCSE',        zh:'IGCSE学习中心',ar:'مركز IGCSE', it:'Hub IGCSE',    de:'IGCSE-Hub'       },
  'hub.as':            { en:'AS & A-Level Study Hub',fr:'Hub A-Level',es:'Hub A-Level',    zh:'A-Level学习中心',ar:'مركز A-Level',it:'Hub A-Level', de:'A-Level-Hub'     },
  'hub.o':             { en:'O-Level Study Hub', fr:'Hub O-Level',   es:'Hub O-Level',      zh:'O-Level学习中心',ar:'مركز O-Level',it:'Hub O-Level', de:'O-Level-Hub'     },

  // ── Search ─────────────────────────────────────────────────────────────
  'search.title':      { en:'Search Questions',  fr:'Rechercher',    es:'Buscar',           zh:'搜索题目',  ar:'بحث',        it:'Cerca',        de:'Suchen'          },
  'search.subject':    { en:'Subject',           fr:'Matière',       es:'Asignatura',       zh:'科目',      ar:'المادة',     it:'Materia',      de:'Fach'            },
  'search.topic':      { en:'Topic / keyword',   fr:'Sujet / mot-clé',es:'Tema / clave',   zh:'主题/关键词', ar:'الموضوع',   it:'Argomento',    de:'Thema'           },
  'search.findBtn':    { en:'Find Questions',    fr:'Trouver',       es:'Buscar',           zh:'查找',      ar:'بحث',        it:'Trova',        de:'Suchen'          },
  'search.upload':     { en:'Upload & Analyse Paper',fr:'Analyser',  es:'Analizar',         zh:'上传分析',  ar:'رفع وتحليل', it:'Carica Analisi',de:'Hochladen'      },
  'search.noResults':  { en:'Select a subject and click Find Questions',fr:'Choisissez une matière',es:'Elige una asignatura',zh:'选择科目后点击搜索',ar:'اختر المادة',it:'Seleziona una materia',de:'Fach auswählen' },
  'search.recent':     { en:'Recent searches',   fr:'Recherches récentes',es:'Recientes',   zh:'最近搜索',  ar:'البحث الأخير',it:'Recenti',      de:'Letzte Suchen'   },

  // ── AI Notes ───────────────────────────────────────────────────────────
  'notes.title':       { en:'AI Study Notes',    fr:'Notes d\'étude IA',es:'Notas de estudio IA',zh:'AI学习笔记',ar:'ملاحظات AI',it:'Note Studio AI',de:'KI-Lernnotizen'  },
  'notes.generate':    { en:'Generate Notes',    fr:'Générer',       es:'Generar',          zh:'生成笔记',  ar:'إنشاء',      it:'Genera Note',  de:'Notizen erstellen'},
  'notes.provider':    { en:'AI provider',       fr:'Fournisseur IA',es:'Proveedor IA',     zh:'AI提供商',  ar:'مزود AI',    it:'Fornitore AI', de:'KI-Anbieter'     },
  'notes.topic':       { en:'Topic',             fr:'Sujet',         es:'Tema',             zh:'主题',      ar:'الموضوع',    it:'Argomento',    de:'Thema'           },
  'notes.flashcards':  { en:'Flashcard quiz',    fr:'Quiz',          es:'Tarjetas',         zh:'闪卡',      ar:'بطاقات',     it:'Flashcard',    de:'Lernkarten'      },
  'notes.download':    { en:'Download PDF',      fr:'Télécharger',   es:'Descargar',        zh:'下载PDF',   ar:'تحميل',      it:'Scarica PDF',  de:'PDF herunterladen'},
  'notes.history':     { en:'Notes history',     fr:'Historique',    es:'Historial',        zh:'笔记历史',  ar:'السجل',      it:'Cronologia',   de:'Verlauf'         },
  'notes.presetTopics':{ en:'Quick topics',      fr:'Sujets rapides',es:'Temas rápidos',    zh:'快速主题',  ar:'مواضيع سريعة',it:'Argomenti veloci',de:'Schnellthemen' },

  // ── Timer ──────────────────────────────────────────────────────────────
  'timer.start':       { en:'Start',             fr:'Démarrer',      es:'Iniciar',          zh:'开始',      ar:'ابدأ',        it:'Avvia',        de:'Starten'         },
  'timer.pause':       { en:'Pause',             fr:'Pause',         es:'Pausar',           zh:'暂停',      ar:'توقف',        it:'Pausa',        de:'Pausieren'       },
  'timer.stop':        { en:'Stop',              fr:'Arrêter',       es:'Detener',          zh:'停止',      ar:'إيقاف',       it:'Ferma',        de:'Stoppen'         },
  'timer.goal':        { en:'Weekly goal',       fr:'Objectif hebdo',es:'Meta semanal',     zh:'每周目标',  ar:'هدف أسبوعي', it:'Obiettivo',    de:'Wochenziel'      },
  'timer.streak':      { en:'Day streak',        fr:'Jours consécutifs',es:'Racha',         zh:'连续天数',  ar:'الأيام المتتالية',it:'Giorni',   de:'Strähne'         },

  // ── My Subjects ────────────────────────────────────────────────────────
  'subjects.add':      { en:'Add subject',       fr:'Ajouter',       es:'Añadir',           zh:'添加科目',  ar:'إضافة مادة', it:'Aggiungi',     de:'Hinzufügen'      },
  'subjects.remove':   { en:'Remove',            fr:'Supprimer',     es:'Eliminar',         zh:'删除',      ar:'إزالة',      it:'Rimuovi',      de:'Entfernen'       },
  'subjects.searchAgain':{ en:'Search again',    fr:'Rechercher',    es:'Buscar de nuevo',  zh:'重新搜索',  ar:'بحث مرة أخرى',it:'Cerca ancora', de:'Erneut suchen'  },

  // ── Settings ───────────────────────────────────────────────────────────
  'settings.title':    { en:'Settings',          fr:'Paramètres',    es:'Ajustes',          zh:'设置',      ar:'الإعدادات',  it:'Impostazioni', de:'Einstellungen'   },
  'settings.profile':  { en:'Profile',           fr:'Profil',        es:'Perfil',           zh:'个人资料',  ar:'الملف الشخصي',it:'Profilo',     de:'Profil'          },
  'settings.language': { en:'Language',          fr:'Langue',        es:'Idioma',           zh:'语言',      ar:'اللغة',      it:'Lingua',       de:'Sprache'         },
  'settings.appearance':{ en:'Appearance',       fr:'Apparence',     es:'Apariencia',       zh:'外观',      ar:'المظهر',     it:'Aspetto',      de:'Aussehen'        },
  'settings.readAloud':{ en:'Read Aloud',        fr:'Lecture audio', es:'Leer en voz alta', zh:'朗读',      ar:'القراءة الصوتية',it:'Lettura voce',de:'Vorlesen'      },
  'settings.data':     { en:'Data & Privacy',    fr:'Données',       es:'Datos',            zh:'数据隐私',  ar:'البيانات',   it:'Dati',         de:'Daten'           },
  'settings.save':     { en:'Save',              fr:'Enregistrer',   es:'Guardar',          zh:'保存',      ar:'حفظ',        it:'Salva',        de:'Speichern'       },
  'settings.saved':    { en:'Saved!',            fr:'Enregistré!',   es:'¡Guardado!',       zh:'已保存!',   ar:'تم الحفظ!',  it:'Salvato!',     de:'Gespeichert!'    },
  'settings.darkMode': { en:'Dark mode',         fr:'Mode sombre',   es:'Modo oscuro',      zh:'深色模式',  ar:'الوضع الداكن',it:'Modalità scura',de:'Dunkelmodus'   },

  // ── Confirm dialogs ─────────────────────────────────────────────────────
  'confirm.cancel':    { en:'Cancel',            fr:'Annuler',       es:'Cancelar',         zh:'取消',      ar:'إلغاء',      it:'Annulla',      de:'Abbrechen'       },
  'confirm.delete':    { en:'Delete',            fr:'Supprimer',     es:'Eliminar',         zh:'删除',      ar:'حذف',        it:'Elimina',      de:'Löschen'         },
  'confirm.clear':     { en:'Clear all',         fr:'Tout effacer',  es:'Borrar todo',      zh:'全部清除',  ar:'مسح الكل',   it:'Cancella tutto',de:'Alle löschen'   },
  'confirm.signOut':   { en:'Sign out',          fr:'Déconnexion',   es:'Cerrar sesión',    zh:'退出',      ar:'تسجيل الخروج',it:'Disconnetti',  de:'Abmelden'        },

  // ── General ─────────────────────────────────────────────────────────────
  'general.loading':   { en:'Loading…',          fr:'Chargement…',   es:'Cargando…',        zh:'加载中…',   ar:'تحميل…',     it:'Caricamento…', de:'Laden…'          },
  'general.error':     { en:'Something went wrong', fr:'Erreur',     es:'Error',            zh:'出错了',    ar:'خطأ',        it:'Errore',       de:'Fehler'          },
  'general.noData':    { en:'Nothing here yet', fr:'Rien encore',    es:'Nada aún',         zh:'暂无内容',  ar:'لا يوجد شيء',it:'Niente ancora', de:'Noch nichts'    },
  'general.searchHere':{ en:'Search…',           fr:'Rechercher…',   es:'Buscar…',          zh:'搜索…',     ar:'بحث…',       it:'Cerca…',       de:'Suchen…'         },
};

const I18nCtx = createContext(null);

export function I18nProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try { return localStorage.getItem('app_lang') || 'en'; } catch { return 'en'; }
  });

  const setLang = useCallback((code) => {
    try { localStorage.setItem('app_lang', code); } catch {}
    setLangState(code);
    // Set document direction for Arabic
    const langObj = LANGUAGES.find(l => l.code === code);
    document.documentElement.dir = langObj?.dir || 'ltr';
    document.documentElement.lang = code;
  }, []);

  const t = useCallback((key, fallback) => {
    const entry = STRINGS[key];
    if (!entry) return fallback ?? key;
    return entry[lang] ?? entry['en'] ?? fallback ?? key;
  }, [lang]);

  // Apply direction on mount
  React.useEffect(() => {
    const langObj = LANGUAGES.find(l => l.code === lang);
    document.documentElement.dir = langObj?.dir || 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <I18nCtx.Provider value={{ t, lang, setLang, languages: LANGUAGES }}>
      {children}
    </I18nCtx.Provider>
  );
}

export function useI18n() {
  const ctx = useContext(I18nCtx);
  if (!ctx) throw new Error('useI18n must be used inside I18nProvider');
  return ctx;
}
